# Generated by Django 3.2.12 on 2024-05-10 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('timestamp', models.TimeField(default=datetime.datetime(2024, 5, 10, 14, 13, 26, 249528))),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=0)),
                ('resume_text', models.TextField(default='')),
                ('job_description_text', models.TextField(default='')),
                ('experience', models.TextField(default='')),
                ('contact_number', models.CharField(default='', max_length=13)),
                ('linkedin_account', models.CharField(default='', max_length=100)),
                ('github_account', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('education', models.TextField(default='')),
                ('resume_skills', models.TextField(default='')),
                ('job_description_skills', models.TextField(default='')),
                ('matching_skills', models.TextField(default='')),
                ('missing_skills', models.TextField(default='')),
                ('matching_percentage', models.FloatField(default=0.0)),
                ('job_field', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_serial_number', models.IntegerField()),
                ('skill', models.TextField(default='')),
                ('selected', models.BooleanField(default=True)),
            ],
        ),
    ]
