# Generated by Django 3.2.12 on 2024-05-13 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCV_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2024, 5, 13, 10, 30, 54, 523772)),
        ),
    ]
