# Generated by Django 3.2.12 on 2024-05-13 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCV_app', '0002_alter_logging_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resume_pdf', models.FileField(upload_to='static\\pdf_files')),
                ('jd_pdf', models.FileField(upload_to='static\\pdf_files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='logging',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2024, 5, 13, 11, 29, 53, 616161)),
        ),
    ]
