# Generated by Django 3.2.12 on 2024-05-13 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCV_app', '0004_auto_20240513_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2024, 5, 13, 13, 5, 43, 365772)),
        ),
    ]
