# Generated by Django 3.2.12 on 2024-05-13 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCV_app', '0006_alter_logging_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2024, 5, 13, 13, 13, 32, 339226)),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='jd_pdf',
            field=models.FileField(upload_to='static\\pdf_files\\'),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='resume_pdf',
            field=models.FileField(upload_to='static\\pdf_files\\'),
        ),
    ]
