# Generated by Django 3.2.12 on 2024-05-13 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCV_app', '0008_auto_20240513_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2024, 5, 13, 13, 44, 19, 630172)),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='pdf',
            field=models.FileField(default=None, upload_to='static/pdf_files/'),
        ),
    ]
