# Generated by Django 3.2.12 on 2024-05-14 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCV_app', '0010_auto_20240514_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2024, 5, 14, 14, 19, 59, 134644)),
        ),
        migrations.AlterField(
            model_name='selectedskills',
            name='resume_serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
