# Generated by Django 3.2.12 on 2024-05-18 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCV_app', '0011_auto_20240514_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='job_profile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='logging',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2024, 5, 18, 14, 49, 2, 432790)),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='job_field',
            field=models.CharField(default='', max_length=100),
        ),
    ]
